preload = ~/Immagini/PXL_20240805_194544484.jpg
wallpaper = eDP-1, ~/Immagini/PXL_20240805_194544484.jpg
wallpaper = HDMI-A-1, ~/Immagini/PXL_20240805_194544484.jpg
#preload = ~/Immagini/wallpapeci.jpg
#wallpaper = eDP-1, ~/Immagini/wallpapeci.jpg
#wallpaper = HDMI-A-1, ~/Immagini/wallpapeci.jpg
ipc = off
splash = false
